
# This is a TOML document 

[client]
showErrorDetails = false 

[theme]
primaryColor = "#F63366"
backgroundColor = "black"

[global]
disableWidgetStateDuplicationWarning = false

showWarningOnDirectExecution = false 